from typing import List, Dict

# In-memory store: mapping session_id to a list of message dictionaries
# Each dictionary represents a message with a "role" and "content"
_sessions: Dict[str, List[Dict[str, str]]] = {}

# Maximum number of conversation turns to keep
# A turn consists of one user message and one assistant message
MAX_TURNS = 5


def get_history(session_id: str) -> List[Dict[str, str]]:
    """
    Retrieves the conversation history for a given session.
    
    Args:
        session_id: The unique identifier for the session.
        
    Returns:
        A list of message dictionaries. Returns an empty list if the session doesn't exist.
    """
    return _sessions.get(session_id, [])


def update_history(session_id: str, user_msg: str, assistant_msg: str) -> None:
    """
    Updates the session history with a new conversation turn (user message + assistant message).
    
    Args:
        session_id: The unique identifier for the session.
        user_msg: The message sent by the user.
        assistant_msg: The response generated by the assistant.
    """
    if session_id not in _sessions:
        _sessions[session_id] = []

    # Append the new turn
    _sessions[session_id].append({"role": "user", "content": user_msg})
    _sessions[session_id].append({"role": "assistant", "content": assistant_msg})

    # Enforce the history limit after updating
    _truncate_history(session_id)


def _truncate_history(session_id: str) -> None:
    """
    Truncates the history to keep only the last MAX_TURNS (10 messages).
    
    Args:
        session_id: The unique identifier for the session.
    """
    if session_id in _sessions:
        history = _sessions[session_id]
        # 5 turns = 10 messages (5 user + 5 assistant)
        max_messages = MAX_TURNS * 2
        if len(history) > max_messages:
            _sessions[session_id] = history[-max_messages:]


def clear_history(session_id: str) -> None:
    """
    Clears the history for a given session.
    
    Args:
        session_id: The unique identifier for the session.
    """
    if session_id in _sessions:
        del _sessions[session_id]
